/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * A contract-first REST API for managing tasks. This API supports full CRUD operations for tasks and provides a custom statistics endpoint that returns aggregated task data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aa020228@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response returned after a successful delete operation
 * @export
 * @interface DeleteResponse
 */
export interface DeleteResponse {
    /**
     * Confirmation message for deletion
     * @type {string}
     * @memberof DeleteResponse
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteResponse interface.
 */
export function instanceOfDeleteResponse(value: object): value is DeleteResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteResponseFromJSON(json: any): DeleteResponse {
    return DeleteResponseFromJSONTyped(json, false);
}

export function DeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function DeleteResponseToJSON(json: any): DeleteResponse {
    return DeleteResponseToJSONTyped(json, false);
}

export function DeleteResponseToJSONTyped(value?: DeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

