/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * A contract-first REST API for managing tasks. This API supports full CRUD operations for tasks and provides a custom statistics endpoint that returns aggregated task data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aa020228@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Input payload used to partially update an existing task
 * @export
 * @interface TaskUpdate
 */
export interface TaskUpdate {
    /**
     * Updated task title
     * @type {string}
     * @memberof TaskUpdate
     */
    title?: string;
    /**
     * Updated assignee name
     * @type {string}
     * @memberof TaskUpdate
     */
    assignee?: string;
    /**
     * Updated task status
     * @type {TaskUpdateStatusEnum}
     * @memberof TaskUpdate
     */
    status?: TaskUpdateStatusEnum;
    /**
     * Updated task priority
     * @type {TaskUpdatePriorityEnum}
     * @memberof TaskUpdate
     */
    priority?: TaskUpdatePriorityEnum;
    /**
     * Updated estimated completion hours
     * @type {number}
     * @memberof TaskUpdate
     */
    estimateHours?: number;
    /**
     * Updated due date
     * @type {Date}
     * @memberof TaskUpdate
     */
    dueDate?: Date;
}


/**
 * @export
 */
export const TaskUpdateStatusEnum = {
    Todo: 'TODO',
    InProgress: 'IN_PROGRESS',
    Done: 'DONE'
} as const;
export type TaskUpdateStatusEnum = typeof TaskUpdateStatusEnum[keyof typeof TaskUpdateStatusEnum];

/**
 * @export
 */
export const TaskUpdatePriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type TaskUpdatePriorityEnum = typeof TaskUpdatePriorityEnum[keyof typeof TaskUpdatePriorityEnum];


/**
 * Check if a given object implements the TaskUpdate interface.
 */
export function instanceOfTaskUpdate(value: object): value is TaskUpdate {
    return true;
}

export function TaskUpdateFromJSON(json: any): TaskUpdate {
    return TaskUpdateFromJSONTyped(json, false);
}

export function TaskUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'assignee': json['assignee'] == null ? undefined : json['assignee'],
        'status': json['status'] == null ? undefined : json['status'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'estimateHours': json['estimateHours'] == null ? undefined : json['estimateHours'],
        'dueDate': json['dueDate'] == null ? undefined : (new Date(json['dueDate'])),
    };
}

export function TaskUpdateToJSON(json: any): TaskUpdate {
    return TaskUpdateToJSONTyped(json, false);
}

export function TaskUpdateToJSONTyped(value?: TaskUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'assignee': value['assignee'],
        'status': value['status'],
        'priority': value['priority'],
        'estimateHours': value['estimateHours'],
        'dueDate': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
    };
}

