/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * A contract-first REST API for managing tasks. This API supports full CRUD operations for tasks and provides a custom statistics endpoint that returns aggregated task data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aa020228@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskStatsTasksByStatus } from './TaskStatsTasksByStatus';
import {
    TaskStatsTasksByStatusFromJSON,
    TaskStatsTasksByStatusFromJSONTyped,
    TaskStatsTasksByStatusToJSON,
    TaskStatsTasksByStatusToJSONTyped,
} from './TaskStatsTasksByStatus';

/**
 * Aggregated statistics derived from the stored tasks
 * @export
 * @interface TaskStats
 */
export interface TaskStats {
    /**
     * Total number of tasks in the system
     * @type {number}
     * @memberof TaskStats
     */
    totalTasks: number;
    /**
     * Number of tasks with status DONE
     * @type {number}
     * @memberof TaskStats
     */
    completedTasks: number;
    /**
     * Number of tasks whose due date has passed and are not done
     * @type {number}
     * @memberof TaskStats
     */
    overdueTasks: number;
    /**
     * Average estimated hours across all tasks
     * @type {number}
     * @memberof TaskStats
     */
    averageEstimateHours: number;
    /**
     * 
     * @type {TaskStatsTasksByStatus}
     * @memberof TaskStats
     */
    tasksByStatus: TaskStatsTasksByStatus;
}

/**
 * Check if a given object implements the TaskStats interface.
 */
export function instanceOfTaskStats(value: object): value is TaskStats {
    if (!('totalTasks' in value) || value['totalTasks'] === undefined) return false;
    if (!('completedTasks' in value) || value['completedTasks'] === undefined) return false;
    if (!('overdueTasks' in value) || value['overdueTasks'] === undefined) return false;
    if (!('averageEstimateHours' in value) || value['averageEstimateHours'] === undefined) return false;
    if (!('tasksByStatus' in value) || value['tasksByStatus'] === undefined) return false;
    return true;
}

export function TaskStatsFromJSON(json: any): TaskStats {
    return TaskStatsFromJSONTyped(json, false);
}

export function TaskStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalTasks': json['totalTasks'],
        'completedTasks': json['completedTasks'],
        'overdueTasks': json['overdueTasks'],
        'averageEstimateHours': json['averageEstimateHours'],
        'tasksByStatus': TaskStatsTasksByStatusFromJSON(json['tasksByStatus']),
    };
}

export function TaskStatsToJSON(json: any): TaskStats {
    return TaskStatsToJSONTyped(json, false);
}

export function TaskStatsToJSONTyped(value?: TaskStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalTasks': value['totalTasks'],
        'completedTasks': value['completedTasks'],
        'overdueTasks': value['overdueTasks'],
        'averageEstimateHours': value['averageEstimateHours'],
        'tasksByStatus': TaskStatsTasksByStatusToJSON(value['tasksByStatus']),
    };
}

