/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * A contract-first REST API for managing tasks. This API supports full CRUD operations for tasks and provides a custom statistics endpoint that returns aggregated task data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aa020228@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Count of tasks grouped by status
 * @export
 * @interface TaskStatsTasksByStatus
 */
export interface TaskStatsTasksByStatus {
    /**
     * Number of tasks in TODO status
     * @type {number}
     * @memberof TaskStatsTasksByStatus
     */
    tODO: number;
    /**
     * Number of tasks in IN_PROGRESS status
     * @type {number}
     * @memberof TaskStatsTasksByStatus
     */
    iNPROGRESS: number;
    /**
     * Number of tasks in DONE status
     * @type {number}
     * @memberof TaskStatsTasksByStatus
     */
    dONE: number;
}

/**
 * Check if a given object implements the TaskStatsTasksByStatus interface.
 */
export function instanceOfTaskStatsTasksByStatus(value: object): value is TaskStatsTasksByStatus {
    if (!('tODO' in value) || value['tODO'] === undefined) return false;
    if (!('iNPROGRESS' in value) || value['iNPROGRESS'] === undefined) return false;
    if (!('dONE' in value) || value['dONE'] === undefined) return false;
    return true;
}

export function TaskStatsTasksByStatusFromJSON(json: any): TaskStatsTasksByStatus {
    return TaskStatsTasksByStatusFromJSONTyped(json, false);
}

export function TaskStatsTasksByStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStatsTasksByStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'tODO': json['TODO'],
        'iNPROGRESS': json['IN_PROGRESS'],
        'dONE': json['DONE'],
    };
}

export function TaskStatsTasksByStatusToJSON(json: any): TaskStatsTasksByStatus {
    return TaskStatsTasksByStatusToJSONTyped(json, false);
}

export function TaskStatsTasksByStatusToJSONTyped(value?: TaskStatsTasksByStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TODO': value['tODO'],
        'IN_PROGRESS': value['iNPROGRESS'],
        'DONE': value['dONE'],
    };
}

