/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * A contract-first REST API for managing tasks. This API supports full CRUD operations for tasks and provides a custom statistics endpoint that returns aggregated task data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aa020228@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A task resource stored in the system
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * Auto-generated unique identifier for the task
     * @type {string}
     * @memberof Task
     */
    readonly id: string;
    /**
     * Short title describing the task
     * @type {string}
     * @memberof Task
     */
    title: string;
    /**
     * Name of the person assigned to the task
     * @type {string}
     * @memberof Task
     */
    assignee: string;
    /**
     * Current progress status of the task
     * @type {TaskStatusEnum}
     * @memberof Task
     */
    status: TaskStatusEnum;
    /**
     * Priority level of the task
     * @type {TaskPriorityEnum}
     * @memberof Task
     */
    priority: TaskPriorityEnum;
    /**
     * Estimated number of hours required to complete the task
     * @type {number}
     * @memberof Task
     */
    estimateHours: number;
    /**
     * Due date for completing the task
     * @type {Date}
     * @memberof Task
     */
    dueDate: Date;
}


/**
 * @export
 */
export const TaskStatusEnum = {
    Todo: 'TODO',
    InProgress: 'IN_PROGRESS',
    Done: 'DONE'
} as const;
export type TaskStatusEnum = typeof TaskStatusEnum[keyof typeof TaskStatusEnum];

/**
 * @export
 */
export const TaskPriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type TaskPriorityEnum = typeof TaskPriorityEnum[keyof typeof TaskPriorityEnum];


/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): value is Task {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('assignee' in value) || value['assignee'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('estimateHours' in value) || value['estimateHours'] === undefined) return false;
    if (!('dueDate' in value) || value['dueDate'] === undefined) return false;
    return true;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'assignee': json['assignee'],
        'status': json['status'],
        'priority': json['priority'],
        'estimateHours': json['estimateHours'],
        'dueDate': (new Date(json['dueDate'])),
    };
}

export function TaskToJSON(json: any): Task {
    return TaskToJSONTyped(json, false);
}

export function TaskToJSONTyped(value?: Omit<Task, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'assignee': value['assignee'],
        'status': value['status'],
        'priority': value['priority'],
        'estimateHours': value['estimateHours'],
        'dueDate': value['dueDate'].toISOString().substring(0,10),
    };
}

