/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * A contract-first REST API for managing tasks. This API supports full CRUD operations for tasks and provides a custom statistics endpoint that returns aggregated task data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aa020228@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Input payload used to create a new task
 * @export
 * @interface TaskCreate
 */
export interface TaskCreate {
    /**
     * Short title describing the task
     * @type {string}
     * @memberof TaskCreate
     */
    title: string;
    /**
     * Name of the person assigned to the task
     * @type {string}
     * @memberof TaskCreate
     */
    assignee: string;
    /**
     * Initial progress status of the task
     * @type {TaskCreateStatusEnum}
     * @memberof TaskCreate
     */
    status: TaskCreateStatusEnum;
    /**
     * Priority level of the task
     * @type {TaskCreatePriorityEnum}
     * @memberof TaskCreate
     */
    priority: TaskCreatePriorityEnum;
    /**
     * Estimated number of hours required to complete the task
     * @type {number}
     * @memberof TaskCreate
     */
    estimateHours: number;
    /**
     * Due date for completing the task
     * @type {Date}
     * @memberof TaskCreate
     */
    dueDate: Date;
}


/**
 * @export
 */
export const TaskCreateStatusEnum = {
    Todo: 'TODO',
    InProgress: 'IN_PROGRESS',
    Done: 'DONE'
} as const;
export type TaskCreateStatusEnum = typeof TaskCreateStatusEnum[keyof typeof TaskCreateStatusEnum];

/**
 * @export
 */
export const TaskCreatePriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;
export type TaskCreatePriorityEnum = typeof TaskCreatePriorityEnum[keyof typeof TaskCreatePriorityEnum];


/**
 * Check if a given object implements the TaskCreate interface.
 */
export function instanceOfTaskCreate(value: object): value is TaskCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('assignee' in value) || value['assignee'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('estimateHours' in value) || value['estimateHours'] === undefined) return false;
    if (!('dueDate' in value) || value['dueDate'] === undefined) return false;
    return true;
}

export function TaskCreateFromJSON(json: any): TaskCreate {
    return TaskCreateFromJSONTyped(json, false);
}

export function TaskCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'assignee': json['assignee'],
        'status': json['status'],
        'priority': json['priority'],
        'estimateHours': json['estimateHours'],
        'dueDate': (new Date(json['dueDate'])),
    };
}

export function TaskCreateToJSON(json: any): TaskCreate {
    return TaskCreateToJSONTyped(json, false);
}

export function TaskCreateToJSONTyped(value?: TaskCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'assignee': value['assignee'],
        'status': value['status'],
        'priority': value['priority'],
        'estimateHours': value['estimateHours'],
        'dueDate': value['dueDate'].toISOString().substring(0,10),
    };
}

