/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tasks
         * @description Returns all tasks currently stored in the system.
         */
        get: operations["TaskService_list"];
        put?: never;
        /**
         * Create a new task
         * @description Creates a new task with the provided task data.
         */
        post: operations["TaskService_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get task statistics
         * @description Returns aggregated task statistics including total task count, completed task count, overdue task count, average estimated hours, and a breakdown of tasks by status.
         */
        get: operations["TaskService_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a task by ID
         * @description Returns a single task resource identified by its unique ID.
         */
        get: operations["TaskService_get"];
        put?: never;
        post?: never;
        /**
         * Delete a task
         * @description Deletes a task identified by its unique ID.
         */
        delete: operations["TaskService_delete"];
        options?: never;
        head?: never;
        /**
         * Partially update a task
         * @description Updates one or more fields of an existing task.
         */
        patch: operations["TaskService_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A task resource stored in the system
         * @example {
         *       "id": "task-1",
         *       "title": "Implement login API",
         *       "assignee": "Alice Kim",
         *       "status": "IN_PROGRESS",
         *       "priority": "HIGH",
         *       "estimateHours": 6,
         *       "dueDate": "2026-04-10"
         *     }
         */
        Task: {
            /**
             * @description Auto-generated unique identifier for the task
             * @example task-1
             */
            readonly id: string;
            /**
             * @description Short title describing the task
             * @example Implement login API
             */
            title: string;
            /**
             * @description Name of the person assigned to the task
             * @example Alice Kim
             */
            assignee: string;
            /**
             * @description Current progress status of the task
             * @example IN_PROGRESS
             * @enum {string}
             */
            status: "TODO" | "IN_PROGRESS" | "DONE";
            /**
             * @description Priority level of the task
             * @example HIGH
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Format: int32
             * @description Estimated number of hours required to complete the task
             * @example 6
             */
            estimateHours: number;
            /**
             * Format: date
             * @description Due date for completing the task
             * @example 2026-04-10
             */
            dueDate: string;
        };
        /** @description Input payload used to create a new task */
        TaskCreate: {
            /**
             * @description Short title describing the task
             * @example Write unit tests
             */
            title: string;
            /**
             * @description Name of the person assigned to the task
             * @example Bob Lee
             */
            assignee: string;
            /**
             * @description Initial progress status of the task
             * @example TODO
             * @enum {string}
             */
            status: "TODO" | "IN_PROGRESS" | "DONE";
            /**
             * @description Priority level of the task
             * @example MEDIUM
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Format: int32
             * @description Estimated number of hours required to complete the task
             * @example 4
             */
            estimateHours: number;
            /**
             * Format: date
             * @description Due date for completing the task
             * @example 2026-04-15
             */
            dueDate: string;
        };
        /** @description Input payload used to partially update an existing task */
        TaskUpdate: {
            /**
             * @description Updated task title
             * @example Update API documentation
             */
            title?: string;
            /**
             * @description Updated assignee name
             * @example Charlie Park
             */
            assignee?: string;
            /**
             * @description Updated task status
             * @example DONE
             * @enum {string}
             */
            status?: "TODO" | "IN_PROGRESS" | "DONE";
            /**
             * @description Updated task priority
             * @example LOW
             * @enum {string}
             */
            priority?: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Format: int32
             * @description Updated estimated completion hours
             * @example 8
             */
            estimateHours?: number;
            /**
             * Format: date
             * @description Updated due date
             * @example 2026-04-20
             */
            dueDate?: string;
        };
        /**
         * @description Aggregated statistics derived from the stored tasks
         * @example {
         *       "totalTasks": 5,
         *       "completedTasks": 2,
         *       "overdueTasks": 1,
         *       "averageEstimateHours": 5.4,
         *       "tasksByStatus": {
         *         "TODO": 1,
         *         "IN_PROGRESS": 2,
         *         "DONE": 2
         *       }
         *     }
         */
        TaskStats: {
            /**
             * Format: int32
             * @description Total number of tasks in the system
             * @example 5
             */
            totalTasks: number;
            /**
             * Format: int32
             * @description Number of tasks with status DONE
             * @example 2
             */
            completedTasks: number;
            /**
             * Format: int32
             * @description Number of tasks whose due date has passed and are not done
             * @example 1
             */
            overdueTasks: number;
            /**
             * @description Average estimated hours across all tasks
             * @example 5.4
             */
            averageEstimateHours: number;
            /** @description Count of tasks grouped by status */
            tasksByStatus: {
                /**
                 * Format: int32
                 * @description Number of tasks in TODO status
                 * @example 1
                 */
                TODO: number;
                /**
                 * Format: int32
                 * @description Number of tasks in IN_PROGRESS status
                 * @example 2
                 */
                IN_PROGRESS: number;
                /**
                 * Format: int32
                 * @description Number of tasks in DONE status
                 * @example 2
                 */
                DONE: number;
            };
        };
        /**
         * @description Response returned after a successful delete operation
         * @example {
         *       "message": "Task deleted successfully"
         *     }
         */
        DeleteResponse: {
            /**
             * @description Confirmation message for deletion
             * @example Task deleted successfully
             */
            message: string;
        };
        /**
         * @description Standard error response schema
         * @example {
         *       "code": 400,
         *       "message": "Bad Request"
         *     }
         */
        ErrorResponse: {
            /**
             * Format: int32
             * @description HTTP status code associated with the error
             * @example 400
             */
            code: number;
            /**
             * @description Human-readable error message
             * @example Bad Request
             */
            message: string;
        };
    };
    responses: never;
    parameters: {
        /**
         * @description Unique identifier of the task
         * @example task-1
         */
        TaskId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    TaskService_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved all tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TaskService_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Task creation payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Task successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request body or validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TaskService_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved task statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStats"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TaskService_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the task
                 * @example task-1
                 */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved the task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid path parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TaskService_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the task
                 * @example task-1
                 */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Invalid path parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TaskService_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the task
                 * @example task-1
                 */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /** @description Partial task update payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Task successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request body or path parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
