/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * A contract-first REST API for managing tasks. This API supports full CRUD operations for tasks and provides a custom statistics endpoint that returns aggregated task data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aa020228@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  TaskStats,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TaskStatsFromJSON,
    TaskStatsToJSON,
} from '../models/index';

/**
 * 
 */
export class StatisticsApi extends runtime.BaseAPI {

    /**
     * Creates request options for taskServiceStats without sending the request
     */
    async taskServiceStatsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/stats`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns aggregated task statistics including total task count, completed task count, overdue task count, average estimated hours, and a breakdown of tasks by status. 
     * Get task statistics
     */
    async taskServiceStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskStats>> {
        const requestOptions = await this.taskServiceStatsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskStatsFromJSON(jsonValue));
    }

    /**
     * Returns aggregated task statistics including total task count, completed task count, overdue task count, average estimated hours, and a breakdown of tasks by status. 
     * Get task statistics
     */
    async taskServiceStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskStats> {
        const response = await this.taskServiceStatsRaw(initOverrides);
        return await response.value();
    }

}
