/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * A contract-first REST API for managing tasks. This API supports full CRUD operations for tasks and provides a custom statistics endpoint that returns aggregated task data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aa020228@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteResponse,
  ErrorResponse,
  Task,
  TaskCreate,
  TaskUpdate,
} from '../models/index';
import {
    DeleteResponseFromJSON,
    DeleteResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TaskFromJSON,
    TaskToJSON,
    TaskCreateFromJSON,
    TaskCreateToJSON,
    TaskUpdateFromJSON,
    TaskUpdateToJSON,
} from '../models/index';

export interface TaskServiceCreateRequest {
    taskCreate: TaskCreate;
}

export interface TaskServiceDeleteRequest {
    id: string;
}

export interface TaskServiceGetRequest {
    id: string;
}

export interface TaskServiceUpdateRequest {
    id: string;
    taskUpdate: TaskUpdate;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Creates request options for taskServiceCreate without sending the request
     */
    async taskServiceCreateRequestOpts(requestParameters: TaskServiceCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskCreate'] == null) {
            throw new runtime.RequiredError(
                'taskCreate',
                'Required parameter "taskCreate" was null or undefined when calling taskServiceCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskCreateToJSON(requestParameters['taskCreate']),
        };
    }

    /**
     * Creates a new task with the provided task data.
     * Create a new task
     */
    async taskServiceCreateRaw(requestParameters: TaskServiceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        const requestOptions = await this.taskServiceCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Creates a new task with the provided task data.
     * Create a new task
     */
    async taskServiceCreate(requestParameters: TaskServiceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.taskServiceCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for taskServiceDelete without sending the request
     */
    async taskServiceDeleteRequestOpts(requestParameters: TaskServiceDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskServiceDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a task identified by its unique ID.
     * Delete a task
     */
    async taskServiceDeleteRaw(requestParameters: TaskServiceDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteResponse>> {
        const requestOptions = await this.taskServiceDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a task identified by its unique ID.
     * Delete a task
     */
    async taskServiceDelete(requestParameters: TaskServiceDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteResponse> {
        const response = await this.taskServiceDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for taskServiceGet without sending the request
     */
    async taskServiceGetRequestOpts(requestParameters: TaskServiceGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskServiceGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single task resource identified by its unique ID.
     * Get a task by ID
     */
    async taskServiceGetRaw(requestParameters: TaskServiceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        const requestOptions = await this.taskServiceGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Returns a single task resource identified by its unique ID.
     * Get a task by ID
     */
    async taskServiceGet(requestParameters: TaskServiceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.taskServiceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for taskServiceList without sending the request
     */
    async taskServiceListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all tasks currently stored in the system.
     * List all tasks
     */
    async taskServiceListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Task>>> {
        const requestOptions = await this.taskServiceListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskFromJSON));
    }

    /**
     * Returns all tasks currently stored in the system.
     * List all tasks
     */
    async taskServiceList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Task>> {
        const response = await this.taskServiceListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for taskServiceUpdate without sending the request
     */
    async taskServiceUpdateRequestOpts(requestParameters: TaskServiceUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taskServiceUpdate().'
            );
        }

        if (requestParameters['taskUpdate'] == null) {
            throw new runtime.RequiredError(
                'taskUpdate',
                'Required parameter "taskUpdate" was null or undefined when calling taskServiceUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TaskUpdateToJSON(requestParameters['taskUpdate']),
        };
    }

    /**
     * Updates one or more fields of an existing task.
     * Partially update a task
     */
    async taskServiceUpdateRaw(requestParameters: TaskServiceUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        const requestOptions = await this.taskServiceUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Updates one or more fields of an existing task.
     * Partially update a task
     */
    async taskServiceUpdate(requestParameters: TaskServiceUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.taskServiceUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
